version: "3.3"

services:
  postgres:
    container_name: database_retazos
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      red_interna:
        ipv4_address: 172.19.0.6

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=davidt@retazosdesol.com
      - PGADMIN_DEFAULT_PASSWORD=azx2134
    ports:
      - 5050:80
    networks:
      red_interna:
        ipv4_address: 172.19.0.5
      red_web:
        ipv4_address: 172.18.0.2

networks:
  red_web:
    ipam:
      config:
        - subnet: 172.18.0.0/16
  red_interna:
    ipam:
      config:
        - subnet: 172.19.0.0/16
