const idName = {
   'Tamaño' : '%3AErY',
   'Debe':'%3B%3CAn',
  'Nombre Prenda' :'%3DKGM',
  'Talla o Tamaño': 'BFN%60' ,
  'Ingreso':'EsqQ',
  'No menor a ':'FcZI',
  'Bolsillos': 'G~%7D%3D' ,
  'Pecho': 'H%3FsE' ,
  'Tamaño o Talla / Formula': 'KC%60d',
  'Tiro':'LRxy',
  'Code': 'LSHA',
  'Proceso':'Mfww',
  'Precio':'NF_V',
  'Detalles': 'NKEL' ,
  'Textos Para Publicaciones':'OkE%7B',
  'Patrón': 'RA%3CS',
  'País de Origen':'T_%3BY' ,
  'Color':'Un%5EA' ,
  'Coleccion Actual':'UoyM',
  'Marca':'UrYX',
  'Suela externa': 'WRNr',
  'Fecha de Pago':'X%3Fea',
  'Ancho ': 'XE%3E%3B',
  'Material':'XKJQ',
  'Abono':'XNyO',
  'Cintura':'X%5Cix' ,
  'Descripcion': 'YGlZ' ,
  'Cadera':'YhkN' ,
  'Orden':'Zv%3CW',
  'Holding':'%5BnyY',
  'Fecha a cobrar':'%5C%3EmO',
  'Pierna':'%5C%60I_' ,
  'Notas de Reparacion':'%5D%3En%3C' ,
  'Monto a Cobrar': '%5DElG' ,
  'Manga':'%5D%7DyW',
  'Suma de Costes':'cS%7Bx',
  'Precio de compra':'c%7DZ%7B' ,
  'Tiempo promedio': 'gN%3C%60',
  'Estados': 'id%3D_',
  'RN':'jI%3C%3A' ,
  'Fecha de coleccion': 'k_mc',
  'Circunferencia':'mHUK',
  'Plantilla interna ':'okpc',
  'Hombro a Hombro':'o%7Dya',
  'Baul':'pyy%5C',
  'Prenda destacada':'sB~z',
  'Precio Minimo ':'tGh%3C' ,
  'proceso de envio':'t~%5Dx',
  'Largo':'u%3DF%3D',
  'Primera Vista':'wlBD',
  'Largo Total':'xBHD',
  'Precio de Envios':'xKpy',
  'Envio pago':'yU%7Dz',
  'tipología de prenda ':'%7BqTk',
  'N':'~%3Bjl',
  'Prenda': 'title'
}


console.log(idName)
